<?php
include('../../dbconnect.php');
$sql = $conn->prepare("SELECT * FROM category_question");
$sql->execute();
$count = 0;
while ($result = $sql->fetch(PDO::FETCH_ASSOC)) {
    $data = '';
    if ($count == 0) {
        $data .= '<div class="tab-pane fade show active" id="F' . $result["id_categoryquestion"] . '" role="tabpanel">';
        $data .= '<table id="question_data_table" class="table align-items-center mb-0">';
        $data .= '<thead>';
        $data .= '<tr class="bg-light">';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">STT</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">Mã câu hỏi</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" scope="col">Hình ảnh</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án A</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án B';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án C</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án D';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án đúng</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Lời giải';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Media';
        $data .= '</th>';
        $data .= '<th class="text-dark text-center">Thao tác</th>';
        $data .= '</tr>';
        $data .= '</thead>';
        $data .= '<tbody id="questions">';
        // $product = $conn->prepare("SELECT * FROM questtion WHERE id_categoryquestion = '" . $result["id_categoryquestion"] . "'");
        $product = $conn->prepare("SELECT * FROM questtion,media WHERE questtion.id_media = media.id_media AND id_categoryquestion = '" . $result["id_categoryquestion"] . "'");
        $product->execute();
        $index = 1;
        while ($sub_result = $product->fetch(PDO::FETCH_ASSOC)) {
            $data .= '<tr id=' . $sub_result['id_question'] . '>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $index . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $sub_result['id_question'] . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex flex-column justify-content-center px-2 py-1">';
            $data .= '<img src="' . $sub_result['name_question'] . '"class="avatar avatar-sm me-3 border-radius-lg" alt="user5">';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option1'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option2'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option3'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option4'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option_correct'] . '</h6>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<p>' . $sub_result['answer'] . '</p>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_media'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-middle text-center">';
            $data .= '<input type="button" class="btn btn-warning text-dark mb-0" href="javascript:;" value="Sửa" name="update"></input>';
            $data .= '<input type="button" class="btn btn-danger text-white mb-0" href="javascript:;" value="Xoá" name="delete"></input>';
            $data .= '</td>';
            $data .= '</tr>';
            $index++;
        }
        $data .= '</tbody>';
        $data .= '</table>';
        $data .= '</div>';
    } else if ($count == 1) {
        $data .= '<div class="tab-pane fade" id="F' . $result["id_categoryquestion"] . '" role="tabpanel">';
        $data .= '<table id="question_data_table" class="table align-items-center mb-0">';
        $data .= '<thead>';
        $data .= '<tr class="bg-light">';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">STT</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">Mã câu hỏi</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" scope="col">Câu hỏi</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án A</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án B';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án C</th>';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án đúng</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Lời giải';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Media';
        $data .= '</th>';
        $data .= '<th class="text-dark text-center">Thao tác</th>';
        $data .= '</tr>';
        $data .= '</thead>';
        $data .= '<tbody id="questions">';

        $product = $conn->prepare("SELECT * FROM questtion,media WHERE questtion.id_media = media.id_media AND id_categoryquestion = '" . $result["id_categoryquestion"] . "'");

        $product->execute();
        $index = 1;
        while ($sub_result = $product->fetch(PDO::FETCH_ASSOC)) {
            $data .= '<tr id=' . $sub_result['id_question'] . '>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $index . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $sub_result['id_question'] . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex flex-column justify-content-center px-2 py-1">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_question'] . '</h6>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option1'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option2'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option3'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option_correct'] . '</h6>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<p>' . $sub_result['answer'] . '</p>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_media'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-middle text-center">';
            $data .= '<input type="button" class="btn btn-warning text-dark mb-0" href="javascript:;" value="Sửa" name="update"></input>';
            $data .= '<input type="button" class="btn btn-danger text-white mb-0" href="javascript:;" value="Xoá" name="delete"></input>';
            $data .= '</td>';
            $data .= '</tr>';
            $index++;
        }
        $data .= '</tbody>';
        $data .= '</table>';
        $data .= '</div>';
    } else if ($count == 2 and $count == 3) {
        $data .= '<div class="tab-pane fade" id="F' . $result["id_categoryquestion"] . '" role="tabpanel">';
        $data .= '<table id="question_data_table" class="table align-items-center mb-0">';
        $data .= '<thead>';
        $data .= '<tr class="bg-light">';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 2%">STT</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 2%">Mã câu hỏi</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" scope="col">Câu hỏi</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án A</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án B';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án C</th>';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án D';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án đúng</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Lời giải';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Media';
        $data .= '</th>';
        $data .= '<th class="text-dark text-center">Thao tác</th>';
        $data .= '</tr>';
        $data .= '</thead>';
        $data .= '<tbody id="questions">';
        $product = $conn->prepare("SELECT * FROM questtion,media WHERE questtion.id_media = media.id_media AND id_categoryquestion = '" . $result["id_categoryquestion"] . "'");

        $product->execute();
        $index = 1;
        while ($sub_result = $product->fetch(PDO::FETCH_ASSOC)) {
            $data .= '<tr id=' . $sub_result['id_question'] . '>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $index . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $sub_result['id_question'] . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex flex-column justify-content-center px-2 py-1">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_question'] . '</h6>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option1'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option2'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option3'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option4'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option_correct'] . '</h6>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<p>' . $sub_result['answer'] . '</p>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_media'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-middle text-center">';
            $data .= '<input type="button" class="btn btn-warning text-dark mb-0" href="javascript:;" value="Sửa" name="update"></input>';
            $data .= '<input type="button" class="btn btn-danger text-white mb-0" href="javascript:;" value="Xoá" name="delete"></input>';
            $data .= '</td>';
            $data .= '</tr>';
            $index++;
        }
        $data .= '</tbody>';
        $data .= '</table>';
        $data .= '</div>';
    } else if ($count == 4) {
        $data .= '<div class="tab-pane fade" id="F' . $result["id_categoryquestion"] . '" role="tabpanel">';
        $data .= '<table id="question_data_table" class="table align-items-center mb-0">';
        $data .= '<thead>';
        $data .= '<tr class="bg-light">';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">STT</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">Mã câu hỏi</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" scope="col">Đoạn văn</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án A</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án B';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án C</th>';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án D';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án đúng</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Lời giải';
        $data .= '</th>';
        $data .= '<th class="text-dark text-center">Thao tác</th>';
        $data .= '</tr>';
        $data .= '</thead>';
        $data .= '<tbody id="questions">';

        $product = $conn->prepare("SELECT * FROM questtion WHERE id_categoryquestion = '" . $result["id_categoryquestion"] . "'");

        $product->execute();
        $index = 1;
        while ($sub_result = $product->fetch(PDO::FETCH_ASSOC)) {
            $data .= '<tr id=' . $sub_result['id_question'] . '>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $index . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $sub_result['id_question'] . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex flex-column justify-content-center px-2 py-1">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_question'] . '</h6>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option1'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option2'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option3'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option4'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option_correct'] . '</h6>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<p>' . $sub_result['answer'] . '</p>';
            $data .= '</td>';
            $data .= '<td class="align-middle text-center">';
            $data .= '<input type="button" class="btn btn-warning text-dark mb-0" href="javascript:;" value="Sửa" name="update"></input>';
            $data .= '<input type="button" class="btn btn-danger text-white mb-0" href="javascript:;" value="Xoá" name="delete"></input>';
            $data .= '</td>';
            $data .= '</tr>';
            $index++;
        }
        $data .= '</tbody>';
        $data .= '</table>';
        $data .= '</div>';
    } else if ($count == 5) {
        $data .= '<div class="tab-pane fade" id="F' . $result["id_categoryquestion"] . '" role="tabpanel">';
        $data .= '<table id="question_data_table" class="table align-items-center mb-0">';
        $data .= '<thead>';
        $data .= '<tr class="bg-light">';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">STT</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">Mã câu hỏi</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" scope="col">Câu hỏi</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án A</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án B';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án C</th>';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án D';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án đúng</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Lời giải';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Media';
        $data .= '</th>';
        $data .= '<th class="text-dark text-center">Thao tác</th>';
        $data .= '</tr>';
        $data .= '</thead>';
        $data .= '<tbody id="questions">';

        $product = $conn->prepare("SELECT * FROM questtion,media WHERE questtion.id_media = media.id_media AND id_categoryquestion = '" . $result["id_categoryquestion"] . "'");

        $product->execute();
        $index = 1;
        while ($sub_result = $product->fetch(PDO::FETCH_ASSOC)) {
            $data .= '<tr id=' . $sub_result['id_question'] . '>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $index . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $sub_result['id_question'] . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex flex-column justify-content-center px-2 py-1">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_question'] . '</h6>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option1'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option2'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option3'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option4'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option_correct'] . '</h6>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<p>' . $sub_result['answer'] . '</p>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_media'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-middle text-center">';
            $data .= '<input type="button" class="btn btn-warning text-dark mb-0" href="javascript:;" value="Sửa" name="update"></input>';
            $data .= '<input type="button" class="btn btn-danger text-white mb-0" href="javascript:;" value="Xoá" name="delete"></input>';
            $data .= '</td>';
            $data .= '</tr>';
            $index++;
        }
        $data .= '</tbody>';
        $data .= '</table>';
        $data .= '</div>';
    } else {
        $data .= '<div class="tab-pane fade" id="F' . $result["id_categoryquestion"] . '" role="tabpanel">';
        $data .= '<table id="question_data_table" class="table align-items-center mb-0">';
        $data .= '<thead>';
        $data .= '<tr class="bg-light">';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">STT</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">Mã câu hỏi</th>';
        $data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" scope="col">Câu hỏi</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án A</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án B';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án C</th>';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án D';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Đáp án đúng</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Lời giải';
        $data .= '</th>';
        $data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder">Media';
        $data .= '</th>';
        $data .= '<th class="text-dark text-center">Thao tác</th>';
        $data .= '</tr>';
        $data .= '</thead>';
        $data .= '<tbody id="questions">';

        $product = $conn->prepare("SELECT * FROM questtion,media WHERE questtion.id_media = media.id_media AND id_categoryquestion = '" . $result["id_categoryquestion"] . "'");

        $product->execute();
        $index = 1;
        while ($sub_result = $product->fetch(PDO::FETCH_ASSOC)) {
            $data .= '<tr id=' . $sub_result['id_question'] . '>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $index . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex px-4 py-1">';
            $data .= '<span>' . $sub_result['id_question'] . '</span>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<div class="d-flex flex-column justify-content-center px-2 py-1">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_question'] . '</h6>';
            $data .= '</div>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option1'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center text-sm">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option2'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option3'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option4'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['option_correct'] . '</h6>';
            $data .= '</td>';
            $data .= '<td>';
            $data .= '<p>' . $sub_result['answer'] . '</p>';
            $data .= '</td>';
            $data .= '<td class="align-center text-center">';
            $data .= '<h6 class="mb-0 text-sm">' . $sub_result['name_media'] . '</h6>';
            $data .= '</td>';
            $data .= '<td class="align-middle text-center">';
            $data .= '<input type="button" class="btn btn-warning text-dark mb-0" href="javascript:;" value="Sửa" name="update"></input>';
            $data .= '<input type="button" class="btn btn-danger text-white mb-0" href="javascript:;" value="Xoá" name="delete"></input>';
            $data .= '</td>';
            $data .= '</tr>';
            $index++;
        }
        $data .= '</tbody>';
        $data .= '</table>';
        $data .= '</div>';
    }
    $count++;
    echo $data;
}
