<?php
include('../../dbconnect.php');
$sql = $conn->prepare("SELECT * FROM historyexam, account, exam WHERE historyexam.account_id = account.account_id AND exam.id_exam = historyexam.id_exam ORDER BY id_historyexam ASC");
$sql->execute();
$data = '';
$data .= '<div class="tab-pane fade show active" id="" role="tabpanel">';
$data .= '<table id="question_data_table" class="table align-items-center mb-0">';
$data .= '<thead>';
$data .= '<tr class="bg-light">';
$data .= '<th class="text-uppercase text-dark text-xs font-weight-bolder" style="width: 5%">STT</th>';
$data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder" style="width: 15%">Tên Thành Viên</th>';
$data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder" style="width: 15%">Tên Đề Thi</th>';
$data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder" style="width: 15%">Điểm</th>';
$data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder" style="width: 15%">Số Câu</th>';
$data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder" style="width: 15%">Nhận Xét</th>';
$data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder" style="width: 15%">Thời Gian Thi</th>';
$data .= '<th class="text-center text-uppercase text-dark text-xs font-weight-bolder" style="width: 15%">Ngày Thi</th>';
$data .= '<th class="text-dark text-center" style="width: 15%">Thao tác</th>';
$data .= '</tr>';
$data .= '</thead>';
$data .= '<tbody id="historyresult">';
$index = 1;
while ($result = $sql->fetch(PDO::FETCH_ASSOC)) {
    $data .= '<tr id=' . $result['id_historyexam'] . '>';
    $data .= '<td>';
    $data .= '<div class="d-flex px-4 py-1">';
    $data .= '<span>' . $index . '</span>';
    $data .= '</div>';
    $data .= '</td>';
    $data .= '<td>';
    $data .= '<div class="d-flex flex-column justify-content-center px-2 py-1">';
    $data .= '<h5 class="text-center">' . $result['name'] . '</h5>';
    $data .= '</div>';
    $data .= '</td>';
    $data .= '<td class="align-center text-center text-sm">';
    $data .= '<h6 class="mb-0 text-sm">' . $result['name_exam'] . '</h6>';
    $data .= '</td>';
    $data .= '<td class="align-center text-center text-sm">';
    $data .= '<h6 class="mb-0 text-sm">' . $result['mark'] . '</h6>';
    $data .= '</td>';
    $data .= '<td class="align-center text-center text-sm">';
    $data .= '<h6 class="mb-0 text-sm">' . $result['number'] . '</h6>';
    $data .= '</td>';
    $data .= '<td class="align-center text-center text-sm">';
    $data .= '<h6 class="mb-0 text-sm">' . $result['comment'] . '</h6>';
    $data .= '</td>';
    $data .= '<td class="align-center text-center text-sm">';
    $data .= '<h6 class="mb-0 text-sm">' . $result['timeExam'] . '</h6>';
    $data .= '</td>';
    $data .= '<td class="align-center text-center text-sm">';
    $data .= '<h6 class="mb-0 text-sm">' . $result['resultTime'] . '</h6>';
    $data .= '</td>';
    $data .= '<td class="align-middle text-center">';
    $data .= '<input type="button" class="btn btn-danger text-white mb-0" href="javascript:;" value="Xoá" name="delete"></input>';
    $data .= '</td>';
    $data .= '</tr>';
    $index++;
}
$data .= '</tbody>';
$data .= '</table>';
$data .= '</div>';
echo $data;
